version: '3'
services:
  app:
    aliases: 'ArmABot'
    build: .
    environment: BOT_TOKEN
    environment: CONNECTION_STRING

  database:
    image: "mariadb"
    environment: 
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ArmABot
      MYSQL_USER: ArmaBot
      MYSQL_PASSWORD: test