// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specificare CultureInfo", Justification = "<In sospeso>", Scope = "member")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specificare StringComparison", Justification = "<In sospeso>", Scope = "member")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Non passare valori letterali come parametri localizzati", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.DBManager.AddAdmin(ArmABot.DBTables.Admin)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Convalidare gli argomenti di metodi pubblici", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.DBManager.AddPoll(ArmABot.DBTables.Poll)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Non passare valori letterali come parametri localizzati", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.DBManager.UpdatePollMessageId(System.Int32,System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Convalidare gli argomenti di metodi pubblici", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Migrations.RebuiltDb.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Convalidare gli argomenti di metodi pubblici", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Migrations.RebuiltDb.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Non passare valori letterali come parametri localizzati", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Program.AddAdminHandler(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specificare CultureInfo", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Program.AddAdminHandler(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specificare CultureInfo", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Program.AddEventHandler(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Non passare valori letterali come parametri localizzati", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Program.AddEventHandler(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Non passare valori letterali come parametri localizzati", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Program.CallbackQueryHandler(System.Object,Telegram.Bot.Args.CallbackQueryEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specificare CultureInfo", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Program.GetPollsHandler(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Non passare valori letterali come parametri localizzati", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Program.GetPollsHandler(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Non passare valori letterali come parametri localizzati", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Program.GetReplyMarkUp(System.Int64,System.Int32)~Telegram.Bot.Types.ReplyMarkups.InlineKeyboardMarkup")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Non passare valori letterali come parametri localizzati", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Non passare valori letterali come parametri localizzati", Justification = "<In sospeso>", Scope = "member", Target = "~M:ArmABot.Program.ResendPollHandler(System.Object,Telegram.Bot.Args.MessageEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1819:Le proprietà non devono restituire matrici", Justification = "<In sospeso>", Scope = "member", Target = "~P:ArmABot.DBTables.User.Specializations")]
